### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by micelle** [micelle/DiSpeak#13]
```
Error: read ECONNRESET
    at exports._errnoException (util.js:1024:11)
    at TCP.onread (net.js:610:25)
```
~この辺りが参考になりそう~
~https://github.com/Dragory/modmailbot/issues?utf8=%E2%9C%93&q=ECONNRESET~
ならなかったゾ

**Comment by micelle** [comment]
このエラーが出る原因としては、DiscordのAPIに接続できない場合に発生するっぽい？
参考：[discord.jsのIssues](https://github.com/discordjs/discord.js/issues?utf8=%E2%9C%93&q=ECONNRESET)
もし発生した場合は『DiSpeak・パソコン・ネットワークの再起動』を試すと良いかも…。

正直、わたしにも分からないエラーです… (ㆀ˘･з･˘)
