### ISSUE TITLE
connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:59960)

### ISSUE THREAD

**Issue by micelle** [micelle/DiSpeak#60]
```
"Error: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:59960)
    at internalConnect (net.js:884:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at defaultTriggerAsyncIdScope (net.js:974:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)"
```
何のエラーなんでしょう……？
棒読みちゃん周り？

**Comment by micelle** [comment]
これも`%appdata%\DiSpeak`に存在しないDiSpeakなので対応しない
