### ISSUE TITLE
Cannot access 'message' before initialization

### ISSUE THREAD

**Issue by micelle** [micelle/DiSpeak#61]
```
ReferenceError: Cannot access 'message' before initialization
    at bouyomiSpeak (file:///C:/Users/***/Documents/Project/discord/DiSpeak/src/js/script.js:1526:15)
    at Client.<anonymous> (file:///C:/Users/***/Documents/Project/discord/DiSpeak/src/js/script.js:1221:5)
    at Client.emit (events.js:223:5)
    at MessageCreateHandler.handle (C:\Users\***\Documents\Project\discord\DiSpeak\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\***\Documents\Project\discord\DiSpeak\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (C:\Users\***\Documents\Project\discord\DiSpeak\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (C:\Users\***\Documents\Project\discord\DiSpeak\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
```
調べます

**Comment by micelle** [comment]
`%appdata%\DiSpeak`に存在しないDiSpeakなので対応しない
