### ISSUE TITLE
channelClass is not a constructor

### ISSUE THREAD

**Issue by micelle** [micelle/DiSpeak#62]
```
TypeError: channelClass is not a constructor
    at ChannelUpdateAction.handle (C:\Users\***\AppData\Local\DiSpeak\app-2.4.4\resources\app\node_modules\discord.js\src\client\actions\ChannelUpdate.js:42:28)
    at ChannelUpdateHandler.handle (C:\Users\***\AppData\Local\DiSpeak\app-2.4.4\resources\app\node_modules\discord.js\src\client\websocket\packets\handlers\ChannelUpdate.js:7:34)
    at WebSocketPacketManager.handle (C:\Users\***\AppData\Local\DiSpeak\app-2.4.4\resources\app\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (C:\Users\***\AppData\Local\DiSpeak\app-2.4.4\resources\app\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (C:\Users\***\AppData\Local\DiSpeak\app-2.4.4\resources\app\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
```
調べます

**Comment by micelle** [comment]
グループDMの名称変更に対応 #46 と関連するエラー。
グループDMの名称を変更する際に発生。
