### ISSUE TITLE
Unable to deserialize cloned data due to invalid or unsupported version.

### ISSUE THREAD

**Issue by micelle** [micelle/DiSpeak#63]
```
Error: Unable to deserialize cloned data due to invalid or unsupported version.
    at EventEmitter../lib/renderer/api/ipc-renderer.ts.ipcRenderer.sendSync (electron/js2c/renderer_init.js:972:20)
    at bouyomiSpeak (file:///C:/Users/***/Documents/Project/discord/DiSpeak/src/js/script.js:1551:17)
    at Client.<anonymous> (file:///C:/Users/***/Documents/Project/discord/DiSpeak/src/js/script.js:1221:5)
    at Client.emit (events.js:223:5)
    at MessageCreateHandler.handle (C:\Users\***\Documents\Project\discord\DiSpeak\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\***\Documents\Project\discord\DiSpeak\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (C:\Users\***\Documents\Project\discord\DiSpeak\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (C:\Users\***\Documents\Project\discord\DiSpeak\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
```
調べます

**Comment by micelle** [comment]
`%appdata%\DiSpeak`に存在しないDiSpeakなので対応しない
